# -*- coding: utf-8 -*-
"""2480.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FbJo59_-ynw7HV65JBmS_7B9V2N6_6SL
"""

import random

li = []
for i in range(3):
  num = random.randint(1, 6)
  li.append(num)
print(li)

if li[0] == li[1]:
  if li[0] == li[2]:
    money = 10000 + li[0]*1000
  else:
    money = 1000 + li[0]*100
elif li[0] == li[2]:
  if li[0] == li[1]:
    money = 10000 + li[0]*1000
  else:
    money = 1000 + li[0]*100
else:
  if li[1] == li[2]:
    money = 1000 + li[1]*100
  else:
    if li[0]>li[1]:
      if li[0]>li[2]:
        money = li[0]*100
      else:
        money = li[2]*100
    else:
      if li[1]>li[2]:
        money = li[1]*100
      else:
        money = li[2]*100

print(money)