# -*- coding: utf-8 -*-
"""10951.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5z7eK7swD9fHMdTY1PdrJtvqers7zar
"""

li = []
for i in range(0, 5):
  a, b = map(int, input("두 정수를 입력하세요(0<a, b<10): ").split())
  li.append(a+b)
for i in range(0, 5):
  print(li[i])