# -*- coding: utf-8 -*-
"""1546.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZX-6bD3ibQwR90XNZDTbrPkjEGNx3wx
"""

subject = int(input("과목의 수를 입력하세요: "))
score = []
fixed_score = []
for i in range(0, subject):
  score.append(int(input()))

for i in range(0, subject):
  fixed_score.append(score[i]/max(score)*100)
print(sum(fixed_score)/subject)