# -*- coding: utf-8 -*-
"""15552.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pqFAtwj-XmRfhOtXp12VkAElGHu2-NeN
"""

import random
ran = random.randint(1, 10) # T를 1,000,000대신 10을 최댓값으로 설정
li = []
print(ran)
for i in range(0, ran):
  p, q = random.randint(1, 100), random.randint(1, 1000)
  print(p, q)
  li.append(p+q)
print('\n')
for i in range(0, ran):
  print(li[i])