# -*- coding: utf-8 -*-
"""2439.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bfglmf1Xj1Wfd0SmiobDKCgjrPLS-eF0
"""

m = int(input())
n = m+1
for i in range(1,n):       # n번째 줄 중에 i번째 줄
  str=""
  for j in range(1, n-i):  #
    str += " "
  for k in range(n-i, n):
    str+="*"
  print(str)