# -*- coding: utf-8 -*-
"""25314.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mp0HGMfOLwTaUVrC_Dxk3tpio9c8cGAo
"""

a = int(input())
b=""
rep = a//4
print(rep)
for i in range(0,rep):
  b += "long "
b +="int"
print(b)