# -*- coding: utf-8 -*-
"""55597.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vn0bm4DUxRzEqvIegEEM9DapvMMP9W8o
"""

classroom = []
hw_no= []       # 숙제를 하지 않은 학생의 출석번호
for i in range(1, 31):
  classroom.append(i)
hw = random.sample(classroom,  28) # 숙제를 한 28명의 학생
print(hw)
for i in range(1, 31):
  if i not in hw:
    hw_no.append(i)
print(hw_no)